// Generated by scripts/generate_tts.py -- do not edit by hand.
//
// The letters that have a spoken "A is for apple" clip, per word set, in
// static/sounds/voice/phrase/<set>/. A letter not listed here simply stays
// quiet, so a set can be filled in a few at a time.
export const PHRASES: Record<string, readonly string[]> = {
	general: [
		'a',
		'b',
		'c',
		'd',
		'e',
		'f',
		'g',
		'h',
		'i',
		'j',
		'k',
		'l',
		'm',
		'n',
		'o',
		'p',
		'q',
		'r',
		's',
		't',
		'u',
		'v',
		'w',
		'x',
		'y',
		'z'
	],
	vehicles: [
		'a',
		'b',
		'c',
		'd',
		'e',
		'f',
		'g',
		'h',
		'i',
		'j',
		'k',
		'l',
		'm',
		'n',
		'o',
		'p',
		'q',
		'r',
		's',
		't',
		'u',
		'v',
		'w',
		'x',
		'y',
		'z'
	]
};
