// Generated by scripts/generate_tts.py -- do not edit by hand.
//
// The letters that have a spoken "A is for apple" clip in
// static/sounds/voice/phrase/. A letter not listed here simply stays
// quiet, so the set can be filled in a few at a time.
export const PHRASES: readonly string[] = ['a', 'b', 'c'];
